
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Pass@123
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: pet_buddy_database_development


test:
  <<: *default
  database: pet_buddy_database_test


production:
  primary: &primary_production
    <<: *default
    database: pet_buddy_database_production
    username: root
    password: <%= ENV["PET_BUDDY_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: pet_buddy_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: pet_buddy_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: pet_buddy_production_cable
    migrations_paths: db/cable_migrate
